name: GITHUB4WOMEN APP 

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' 

    - name: Restore dependencies
      run: dotnet restore **/*.csproj

    - name: Build
      run: dotnet build **/*.csproj --no-restore

 my_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set execute permissions for my-script.sh
      run: chmod +x ./github4women/scripts/my-script.sh

    - name: Run my script
      run: ./github4women/scripts/my-script.sh